# Generated by Django 4.0 on 2023-11-11 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barangay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brgy_name', models.CharField(max_length=255)),
                ('lat', models.IntegerField()),
                ('long', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
                ('brgy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_brgy', to='management.barangay')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_gender', to='management.gender')),
            ],
        ),
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
                ('brgy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leader_brgy', to='management.barangay')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leader_gender', to='management.gender')),
            ],
        ),
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cluster_leader', to='management.leader')),
                ('members', models.ManyToManyField(related_name='cluster_member', to='management.Member')),
            ],
        ),
    ]
