# Generated by Django 4.0 on 2023-11-11 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barangay',
            name='lat',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='barangay',
            name='long',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
