# Generated by Django 4.0 on 2023-11-13 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_barangay_lat_alter_barangay_long'),
    ]

    operations = [
        migrations.AddField(
            model_name='barangay',
            name='brgy_voter_population',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
