# Generated by Django 4.0 on 2023-11-18 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_barangay_brgy_voter_population'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddedLeaders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leader', models.CharField(max_length=255)),
                ('date_time_registered', models.DateTimeField(auto_now_add=True)),
                ('date_registered', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AddedMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.CharField(max_length=255)),
                ('date_time_registered', models.DateTimeField(auto_now_add=True)),
                ('date_registered', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
