# Generated by Django 4.0 on 2024-01-25 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_addedleaders_addedmembers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sitio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('population', models.IntegerField(blank=True, default=0, null=True)),
                ('lat', models.IntegerField(blank=True, null=True)),
                ('long', models.IntegerField(blank=True, null=True)),
                ('brgy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brgy_sitio', to='management.barangay')),
            ],
        ),
    ]
