# Generated by Django 4.0 on 2024-01-25 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_sitio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barangay',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='barangay',
            name='long',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sitio',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sitio',
            name='long',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
