# Generated by Django 4.0 on 2024-01-28 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_alter_barangay_lat_alter_barangay_long_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='barangay',
            options={'ordering': ['brgy_name']},
        ),
        migrations.AddField(
            model_name='leader',
            name='sitio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='leader_sitio', to='management.sitio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='sitio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='member_sitio', to='management.sitio'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
                ('brgy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_brgy', to='management.barangay')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_gender', to='management.gender')),
            ],
        ),
    ]
