# Generated by Django 4.0 on 2024-01-30 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_alter_barangay_options_leader_sitio_member_sitio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leader',
            name='sitio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leader_sitio', to='management.sitio'),
        ),
        migrations.AlterField(
            model_name='member',
            name='sitio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_sitio', to='management.sitio'),
        ),
    ]
