# Generated by Django 3.1 on 2024-02-11 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0010_auto_20240205_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.CharField(max_length=400)),
                ('is_seen', models.BooleanField(blank=True, default=False, null=True)),
                ('removed', models.BooleanField(blank=True, default=False, null=True)),
                ('date', models.DateField()),
                ('date_time', models.DateTimeField()),
                ('identifier', models.CharField(max_length=500)),
            ],
            options={
                'ordering': ['-date_time'],
            },
        ),
        migrations.AddField(
            model_name='individual',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_individual', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leader',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='leader_user', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='member_user', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='individual',
            name='brgy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='individual_brgy', to='management.barangay'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='individual_gender', to='management.gender'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='sitio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='individual_sitio', to='management.sitio'),
        ),
        migrations.CreateModel(
            name='Registrants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateField()),
                ('date_time', models.DateTimeField()),
                ('age', models.IntegerField()),
                ('image', models.ImageField(upload_to='images/')),
                ('brgy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.barangay')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.gender')),
                ('sitio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.sitio')),
            ],
        ),
    ]
