# Generated by Django 3.1 on 2024-02-09 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_auto_20240205_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registrants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateField()),
                ('date_time', models.DateTimeField()),
                ('age', models.IntegerField()),
                ('image', models.ImageField(upload_to='images/')),
                ('brgy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.barangay')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.gender')),
                ('sitio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.sitio')),
            ],
        ),
    ]
