# Generated by Django 3.1 on 2024-02-11 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_auto_20240211_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrants',
            name='sitio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.sitio'),
        ),
    ]
