# Generated by Django 3.1 on 2024-02-15 07:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='group',
            field=models.CharField(default='group', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='individual',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 15, 7, 13, 10, 960135, tzinfo=utc)),
        ),
    ]
