# Generated by Django 3.1 on 2024-02-19 01:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0015_auto_20240215_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalVoterPopulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('population', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 19, 1, 31, 28, 272534, tzinfo=utc)),
        ),
    ]
