# Generated by Django 3.1 on 2024-02-20 01:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0016_auto_20240219_0921'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCodeAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('brgy', models.CharField(max_length=255)),
                ('sitio', models.CharField(max_length=255)),
                ('group', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('date_time', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 20, 2, 9, 33, 582097, tzinfo=utc)),
        ),
    ]
