# Generated by Django 3.1 on 2024-03-04 16:19

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0019_auto_20240304_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderconnectmemberrequest',
            name='requests',
            field=models.ManyToManyField(blank=True, null=True, related_name='leader_connecting_request', to='management.Leader'),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 4, 16, 29, 11, 366159, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='LeadersRequestConnect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leader_connect_request', to='management.leader')),
                ('requests', models.ManyToManyField(blank=True, null=True, related_name='leader_connecting_member', to='management.Member')),
            ],
        ),
    ]
