# Generated by Django 3.1 on 2024-03-12 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0020_auto_20240305_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='leader',
            name='encryption',
            field=models.SlugField(default='none', max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='encryption',
            field=models.SlugField(default='none', max_length=2000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leaderconnectmemberrequest',
            name='requests',
            field=models.ManyToManyField(related_name='leader_connecting_request', to='management.Leader'),
        ),
        migrations.AlterField(
            model_name='leadersrequestconnect',
            name='requests',
            field=models.ManyToManyField(related_name='leader_connecting_member', to='management.Member'),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
