# Generated by Django 3.1 on 2024-03-13 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0021_auto_20240312_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leader',
            name='encryption',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='member',
            name='encryption',
            field=models.CharField(max_length=2000),
        ),
    ]
