# Generated by Django 3.1 on 2024-03-13 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0022_auto_20240313_0938'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmbiguousVoters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('voters', models.ManyToManyField(blank=True, null=True, related_name='ambiguous_voters', to='management.Individual')),
            ],
        ),
    ]
