# Generated by Django 4.2.16 on 2024-09-29 02:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0023_ambiguousvoters'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarangayElectionContender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rank', models.CharField(max_length=255)),
                ('vote_count', models.IntegerField(default=0)),
                ('party', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ElectionContender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rank', models.CharField(max_length=255)),
                ('vote_count', models.IntegerField(default=0)),
                ('party', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ElectionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Religion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='individual',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='individual',
            name='house_image',
            field=models.ImageField(blank=True, null=True, upload_to='houses/'),
        ),
        migrations.AddField(
            model_name='individual',
            name='is_cockroach',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='individual',
            name='is_deceased',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='individual',
            name='is_father',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='individual',
            name='is_leader',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='individual',
            name='is_oot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='individual',
            name='is_parent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='individual',
            name='is_swing_voter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='individual',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='individual',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='individual',
            name='long',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='individual',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='individual',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='individual',
            name='suffix',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='addedleaders',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='addedmembers',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ambiguousvoters',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ambiguousvoters',
            name='voters',
            field=models.ManyToManyField(related_name='ambiguous_voters', to='management.individual'),
        ),
        migrations.AlterField(
            model_name='barangay',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='gender',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='individual',
            name='brgy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='individual_brgy', to='management.barangay'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='individual_gender', to='management.gender'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='group',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='individual',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='individual',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_individual', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leader',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='leaderconnectmemberrequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='leadersrequestconnect',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='member',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='qrcodeattendance',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='registrants',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sitio',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='totalvoterpopulation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='SitioRemark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.CharField(max_length=500)),
                ('sitio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.sitio')),
            ],
        ),
        migrations.CreateModel(
            name='IndividualSpouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('individual', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='individuals_spouse', to='management.individual')),
                ('spouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.individual')),
            ],
        ),
        migrations.CreateModel(
            name='IndividualSiblings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('individual', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='individuals_sibling', to='management.individual')),
                ('siblings', models.ManyToManyField(blank=True, to='management.individual')),
            ],
        ),
        migrations.CreateModel(
            name='IndividualParents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('individual', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='individuals_parent', to='management.individual')),
                ('parents', models.ManyToManyField(blank=True, to='management.individual')),
            ],
        ),
        migrations.CreateModel(
            name='IndividualOffspring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('children', models.ManyToManyField(blank=True, to='management.individual')),
                ('individual', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='individuals_offspring', to='management.individual')),
            ],
        ),
        migrations.CreateModel(
            name='IndividualLeaderCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('individual', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='individual_leader', to='management.individual')),
                ('members', models.ManyToManyField(related_name='individual_leader_members', to='management.individual')),
            ],
        ),
        migrations.CreateModel(
            name='ElectionResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('election_year', models.DateField()),
                ('contenders', models.ManyToManyField(blank=True, to='management.electioncontender')),
                ('election_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='election_type_result', to='management.electiontype')),
            ],
        ),
        migrations.CreateModel(
            name='Church',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(blank=True, null=True)),
                ('long', models.FloatField(blank=True, null=True)),
                ('brgy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.barangay')),
                ('sitio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.sitio')),
            ],
        ),
        migrations.CreateModel(
            name='BrgySchoolHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rank', models.CharField(max_length=255)),
                ('brgy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brgy_school_head', to='management.barangay')),
            ],
        ),
        migrations.CreateModel(
            name='BrgyOfficial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rank', models.CharField(max_length=255)),
                ('brgy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brgy_official', to='management.barangay')),
            ],
        ),
        migrations.CreateModel(
            name='BarangayRemark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.CharField(max_length=500)),
                ('brgy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.barangay')),
            ],
        ),
        migrations.CreateModel(
            name='BarangayFigures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brgy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.barangay')),
                ('officials', models.ManyToManyField(blank=True, related_name='officials_barangay', to='management.brgyofficial')),
                ('school_heads', models.ManyToManyField(blank=True, to='management.brgyschoolhead')),
            ],
        ),
        migrations.CreateModel(
            name='BarangayElectionResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('election_year', models.DateField(blank=True, null=True)),
                ('brgy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.barangay')),
                ('contenders', models.ManyToManyField(blank=True, to='management.barangayelectioncontender')),
                ('election_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='management.electiontype')),
            ],
        ),
        migrations.AddField(
            model_name='individual',
            name='occupation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.occupation'),
        ),
        migrations.AddField(
            model_name='individual',
            name='religion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='management.religion'),
        ),
    ]
