from django.urls import path
from management import views


urlpatterns = [
    path('home/', views.homepage, name='homepage'),

    path('brgy/<str:brgy_name>/', views.barangay_members, name='member-brgy'),
    path('sitio/<int:id>/', views.sitio_profile, name='sitio-profile'),

    path('dashboard/', views.dashboard, name='dashboard'),
    path('leader/profile/<str:name>/<str:username>/', views.leader_cluster, name='cluster'),
    path('member-profile/<str:name>/<int:id>/', views.member_profile, name='member-profile'),
    path('add-brgy/', views.add_barangay, name='add-brgy'),
    path('add-members/', views.add_members, name='add-members'),
    path('clusters/', views.clusters, name='clusters'),
    path('add-leader/', views.add_leader, name='add-leader'),
    path('reports/', views.reports, name='reports'),
    path('registration/', views.registration_validation, name='registration'),
    path('registrants/', views.registrants, name='registrants'),
    path('attendance/qr-code-scan/', views.qr_code_scanner, name='qr-code-attendance'),

    path('report/member-count-brgy/', views.member_count_per_brgy, name='member-count-brgy'),
    path('report/leaders/member/None/', views.no_members_leader, name='no-member-leader'),
    path('report/members/leader/None/', views.leaderless_members, name='leaderless-members'),
    path('report/no-member-brgys/', views.no_member_barangays, name='no-member-brgys'),
    path('report/members/all/', views.all_members_individuals_report, name='all-members-report'),
    path('report/brgy/members/', views.members_per_brgy_report, name='per-brgy-members'),
    path('report/cluster/', views.leader_members_report, name='cluster-report'),
    path('report/members/', views.all_members_report, name='members-report'),
    path('report/leaders/', views.all_leaders_report, name='leaders-report'),
    path('attendance/list/', views.attendance_list, name='attendance-list'),
    path('report/sitios/', views.sitios_report, name='sitio-report'),
    path('report/ambiguous-voters/', views.ambiguous_members_report, name='ambiguous-voters'),

    path('report/no-member-brgys/download-pdf', views.no_member_barangays_pdf, name='no-member-brgys-pdf'),
    path('report/member-count-brgy/download-pdf', views.member_count_per_brgy_pdf, name='member-count-brgy-pdf'),
    path('report/leaders/member/None/download-pdf', views.no_members_leader_pdf, name='no-member-leader-pdf'),
    path('report/brgy/members/download-pdf/', views.members_per_brgy_report_pdf, name="per-brgy-members-pdf"),
    path('report/members/leader/None/download-pdf', views.leaderless_members_pdf, name='leaderless-members-pdf'),
    path('report/cluster/download-pdf', views.leader_members_report_pdf, name='cluster-report-pdf'),
    path('report/members/all/download-pdf/', views.all_members_individuals_report_pdf, name='all-members-report-pdf'),
    path('report/leaders/download-pdf', views.all_leaders_report_pdf, name='leaders-report-pdf'),
    path('report/members/download-pdf', views.all_members_report_pdf, name='members-report-pdf'),
    path('attendance/list/download-pdf/', views.attendance_list_pdf, name='attendance-list-pdf'),
    path('report/sitios/download-pdf', views.sitios_report_pdf, name='sitio-report-pdf'),
    path('report/ambiguous-voters-pdf/', views.ambiguous_members_report_pdf, name='ambiguous-voters-pdf'),

    path('report/cluster-filtered/download-pdf', views.leader_members_report_filtered_pdf,
         name='cluster-filtered-report-pdf'),
    path('report/brgy-filtered/members/download-pdf/', views.members_filtered_per_brgy_report_pdf,
       name="per-filtered-brgy-members-pdf"),
    path('attendance/list-daily/download-pdf/', views.attendance_list_filtered_daily_pdf,
       name='attendance-list-daily-pdf'),
    path('report/sitios/download-filtered-pdf', views.sitios_report_filtered_pdf, name='sitio-report-filtered-pdf'),
    path('report/ambiguous-voters-filtered-pdf/', views.ambiguous_members_filter_report_pdf,
         name='ambiguous-voters-filtered-pdf'),

    path('function/<str:member_id>/<str:leader_id>/', views.tag_leader_member, name='tag-leader'),
    path('change-brgy-name/', views.change_brgy_name, name='change-brgy-name'),
    path('promote/<str:username>/', views.promote_to_leader, name='promote-member-to-leader'),
    path('add-sitio/', views.add_sitio, name='add-sitio'),
    path('get_filtered_sitios/', views.get_filtered_sitios, name='get_filtered_sitios'),
    path('get_filtered_sitios_using_brgy_id/', views.get_filtered_sitios_using_brgy_id,
         name='get-filtered-sitios-using-brgy-id'),
    path('get_filtered_leaders/', views.get_filtered_leaders, name='get_filtered_leaders'),
    path('', views.authentication, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('create-individuals/', views.create_individuals, name='create-individuals'),
    path('create-json/', views.create_json, name='create-json'),
    path('load-json/', views.load_json, name='load-json'),
    path('registration/confirm/member/<str:username>/', views.confirm_registration_member, name='confirm-member'),
    path('registration/confirm/leader/<str:username>/', views.confirm_registration_leader, name='confirm-leader'),
    path('registration/confirm/admin/<str:username>/', views.confirm_registrant_as_admin_and_leader,
         name='confirm-admin'),
    path('deny-registration/<str:username>/', views.deny_registration, name='deny-registration'),
    path('deny-registration/illegible-image/<str:username>/', views.deny_registration_invalid_image,
         name='deny-registration-illegible-image'),
    path('deny-registration/invalid-email/<str:username>/', views.deny_registration_invalid_email,
         name='deny-registration-invalid-email'),
    path('associate/<str:leader_username>/<str:member_username>/', views.associate_member_to_leader,
         name='associate-member'),
    path('remove/<str:leader_username>/<str:member_username>/', views.remove_member_from_leader,
         name='unassociated-member'),
    path('seen-notifications/', views.seen_notifications, name='seen-notifications'),
    path('delete-notification/<str:title>/<int:id>/', views.remove_notification, name='delete-notification'),
    path('request/connect/<str:member>/<str:leader>/', views.add_member_leader_request, name='request-connect'),
    path('revert-request/connect/<str:member>/<str:leader>/', views.revert_member_leader_request,
         name='revert-request-connect'),
    path('accept/request/<str:leader>/<str:member>/', views.accept_leader_connect_request, name='accept-connect'),
    path('deny/request/<str:leader>/<str:member>/', views.deny_leader_connect_request, name='deny-connect'),
    path('encrypt-members/',  views.encrypt_members, name='encrypt-members'),
    path('suspect/<str:username>/', views.suspect_voter, name='suspect-voter'),
    path('un-suspect/<str:username>/', views.unsuspect_voter, name='unsuspect-voter'),

    path('notifications/', views.notifications_async, name='notifications'),
    path("profile/leader/<str:encryption>/", views.non_admin_leader_profile, name='profile-leader'),
    path("profile/member/<str:encryption>/", views.non_admin_member_profile, name='profile-member'),
    path('forgot-password/', views.forgot_password, name='forgot-password'),
    path('enter-token/<str:email>/', views.enter_token, name='enter-token'),
    path('change-password/<str:email>/<str:token_str>/', views.change_password, name='change-password'),

    path('individual/<int:individual_id>/', views.individual_view, name='individual'),
    path('individual-family-conf/<int:individual_id>/', views.individual_family_input, name='individual-family-conf'),
    path('individual-encode/', views.individual_input, name='individual-input'),
    path('election-results/', views.election_results_func, name='election-results'),
    path('church/', views.encode_church, name='church-input'),

    # htmx request
    path('htmx-sitio-result/', views.htmx_sitio_options, name='htmx-sitio-options'),
    path('htmx-sitio-result-one-ring/', views.htmx_sitio_options_one_ring, name='htmx-sitio-options-one-ring'),

    path('htmx-party-input/', views.brgy_profile_htmx_trigger_party_input, name='htmx-party-input'),
    path('htmx-select-party/', views.trigger_select_contender_party, name='htmx-select-party'),
    path('htmx-captain-rank-input/', views.captain_rank_manual_input, name='htmx-captain-input'),
    path('htmx-captain-ranks/', views.brgy_captain_existing_ranks, name='htmx-existing-ranks'),
    path('htmx-election-type-input/', views.election_type_input_trigger, name='htmx-election-type-input'),
    path('htmx-existing-type', views.election_existing_type_trigger, name='htmx-existing-election-type'),
    path('htmx-official-rank-input/', views.brgy_official_rank_input_trigger, name='htmx-brgy-official-rank-input'),
    path('htmx-existing-brgy-official-rank/', views.brgy_official_existing_rank, name='htmx-brgy-official-existing-ranks'),
    path('htmx-school-head-input/', views.school_heads_input_trigger, name='htmx-school-head-input-trigger'),
    path('htmx-existing-school-head-rank/', views.school_head_existing_rank, name='htmx-existing-school-head-ranks'),
    path('htmx-congress-rank-input/', views.congressional_add_new_rank_trigger, name='htmx-congress-rank-input'),
    path('htmx-existing-congress-rank/', views.congress_select_existing_rank, name='htmx-congress-existing-rank'),
    path('htmx-congress-party-input/', views.congress_party_input, name='htmx-congress-party-input'),
    path('htmx-congress-existing-party/', views.congress_existing_party, name='htmx-congress-existing-party'),
    path('htmx-board-member-rank-input/', views.board_member_rank_input, name='htmx-board-member-rank-input'),
    path('htmx-board-member-existing-rank/', views.board_member_existing_rank, name='htmx-board-member-existing-rank'),
    path('htmx-board-member-party-input/', views.board_member_party_input, name='htmx-board-member-party-input'),
    path('htmx-board-member-existing-party/', views.board_member_existing_party, name='htmx-board-member-existing-party'),
    path('htmx-mayoral-rank-input/', views.mayoral_rank_input, name='htmx-mayoral-rank-input'),
    path('htmx-mayoral-existing-rank/', views.mayoral_existing_rank, name='htmx-mayoral-existing-rank'),
    path('htmx-mayoral-party-input/', views.mayoral_party_input, name='htmx-mayoral-party-input'),
    path('htmx-mayoral-existing-party/', views.mayoral_existing_party, name='htmx-mayoral-existing-party'),

    path('one-ring/<int:individual_id>/', views.one_ring, name='one-ring'),

    # APIS
    path('endpoints/', views.endpoints, name='endpoint'),
]
